#!/usr/bin/env bash
# 100-process_and_pid_file

trap 'echo Y U no love me?!' SIGINT
trap 'rm $file; exit' SIGQUIT
trap 'echo I hate the kill command; rm $file; exit' SIGTERM

echo "$$" > /var/run/myscript.pid
while true; do
	echo To infinity and beyond
	sleep 2
done
