#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost is resolving on 127.0.0.2
#   - facebook.com  is resolving on  8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

